codecov:
  require_ci_to_pass: true

github_checks: false

coverage:
  precision: 2
  round: down
  range: "40...100"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

status:
  patch:
    informational: false
    default:
      target: 0.70
      threshold: 1%
      if_not_found: failure
